import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React, { useRef, useEffect, useState } from 'react'
import Enhancement from '@/components/Enhancement';

export default function myApp() {

  // Refference for the video tag
  const videoRef = useRef<HTMLVideoElement>(null);
  const [s, setStream] = useState<MediaStream | null>(null);
  
  // Execute after rendering
  useEffect(() => {
    const setVideoStream = async (stream: MediaStream | null) => {
      stream = await navigator.mediaDevices.getUserMedia({ video: true });
      if (videoRef.current){
        videoRef.current.srcObject = stream;
        setStream(stream);
      }
    }
    setVideoStream(s);
  }, [videoRef])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            original image
          </p>
          <p>
            enhanced image
          </p>
        </div>
        <div>
          <video ref={videoRef} autoPlay/>
          <Enhancement
          video = {s}
          />
        </div>
      </main>
    </>
  )
}
